import * as sim from './physics.js';
import * as neural from './neural.js';
import { createKitchenView } from './scene3d.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#world'), circuit=$('#circuit'), cx=circuit.getContext('2d');
const app={world:null,paused:false,last:performance.now(),acc:0,selected:0,mode:'autopilot',mission:'balance',forces:Array(8).fill(0),judge:null,training:false,learned:null};
function showSceneError(error){
  $('#sceneLoading').hidden=true;
  $('#sceneError').hidden=false;
  $('#sceneErrorText').textContent=error?.message||'WebGL could not start or its context was lost.';
  $('#statusText').textContent='3D view unavailable';
  $('#statusDot').classList.add('paused');
}
let kitchenView;
try{
  kitchenView=createKitchenView(canvas,{
    onTarget:(x,y)=>{if(app.judge||!app.world)return;const p=typeof x==='object'?x:{x,y};if(Number.isFinite(p.x))app.world.target.x=p.x;if(Number.isFinite(p.y))app.world.target.y=p.y;clampTarget();updateTargetInputs();$('#sceneHint').textContent=`Target moved to ${app.world.target.x.toFixed(1)}, ${app.world.target.y.toFixed(1)}`},
    onSelectFly:index=>{if(!app.world||!Number.isInteger(index)||index<0||index>=app.world.flies.length)return;app.selected=index;renderFlyPicker()},
    onError:showSceneError
  });
  $('#sceneLoading').hidden=true;
}catch(error){
  showSceneError(error);
  kitchenView={render(){},resetCamera(){},setCameraPreset(){},dispose(){}};
}

async function loadEvidence(){for(const path of ['./data/circuit.json']){try{const r=await fetch(path);if(r.ok)return await r.json()}catch{}}return null}
const evidence=await loadEvidence();
if(!evidence)throw new Error('Required anatomical circuit data could not be loaded.');
let neuralSwarm=neural.createSwarm(evidence,{agentCount:8,seed:7401});
let blankSwarm=neural.createSwarm(evidence,{agentCount:8,seed:7401});
async function restoreLearned(){let local=null;try{local=localStorage.getItem('fly-swarm-learned');if(local){neuralSwarm=neural.deserializeSwarm(evidence,JSON.parse(local));app.learned=true;return}}catch(error){console.warn('Ignoring stale saved readout:',error);try{localStorage.removeItem('fly-swarm-learned')}catch{}}try{const r=await fetch('./evidence/trained-session.json');if(!r.ok)throw new Error(`HTTP ${r.status}`);neuralSwarm=neural.deserializeSwarm(evidence,await r.json());app.learned=true}catch(error){console.warn('Shipped trained session unavailable:',error)}}
await restoreLearned();
const circuitView=(()=>{const pn=evidence.neurons.filter(n=>n.role==='projection_neuron').slice(0,8),kc=evidence.neurons.filter(n=>n.role==='kenyon_cell').slice(0,18),ids=new Set([...pn,...kc].map(n=>String(n.id))),edges=evidence.edges.filter(e=>e.relation==='pn_to_kc'&&ids.has(String(e.pre))&&ids.has(String(e.post)));return{pn,kc,edges}})();
$('#evidenceSummary').textContent=`Evidence: ${evidence.neurons.length.toLocaleString()} neurons · ${evidence.edges.length.toLocaleString()} anatomical edges.`;
fetch('./evidence/experiment-results.json').then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(x=>{const h=x.summaryByGroup?.learned?.heldOutInterpolation,s=x.summaryByGroup?.learned?.stressExtrapolation;if(h&&s)$('#evidenceSummary').textContent+=` Frozen evaluation: ${h.successes}/${h.trials} held-out; ${s.successes}/${s.trials} stress.`}).catch(()=>{$('#evidenceSummary').textContent+=' Frozen evaluation file unavailable.'});
function hashSeed(s){let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0}
function reset(){const mass=+$('#massRange').value;app.world=sim.createWorld({seed:hashSeed($('#seedInput').value),mass,target:{x:app.mission==='carry'?1.7:0,y:app.mission==='carry'?1.7:2.05},tilt:0,disabled:[]});app.last=performance.now();app.acc=0;app.judge=null;updateScore(null);updateTargetInputs()}
function control(w){if(app.mode==='autopilot')return sim.baselineForces(w);return neural.swarmForces(app.mode==='untrained'?blankSwarm:neuralSwarm,w)}
function updateUI(){const w=app.world;$('#balanceReadout').textContent=`${(w.angle*180/Math.PI).toFixed(1)}°`;$('#heightReadout').textContent=w.y.toFixed(2);$('#timeReadout').textContent=`${w.time.toFixed(1)} s`;const f=w.flies[app.selected],lift=w.flies.reduce((s,x)=>s+x.fy,0),load=w.mass*sim.GRAVITY,effort=w.flies.reduce((s,x)=>s+Math.hypot(x.fx,x.fy),0),swarm=app.mode==='untrained'?blankSwarm:neuralSwarm,weights=swarm.agents[app.selected].readout.flat(),changed=weights.filter(v=>Math.abs(v)>1e-7).length,norm=Math.hypot(...weights);$('#forceReadout').textContent=`${lift.toFixed(1)} / ${load.toFixed(1)} · Σ${effort.toFixed(1)}`;$('#senseHeight').textContent=(w.target.y-w.y>=0?'+':'')+(w.target.y-w.y).toFixed(2);$('#senseTilt').textContent=`${(w.angle*180/Math.PI).toFixed(1)}°`;$('#senseVelocity').textContent=w.vy.toFixed(2);$('#senseThrust').textContent=`${Math.round((f?.fy||0)/8*100)}%`;$('#readoutSummary').textContent=app.mode==='autopilot'?'Engineering controller active; neural graph is idle.':`Fly ${app.selected+1}: ${changed} changed readout weights · norm ${norm.toFixed(2)} · sample KC ${swarm.topo.kc[0]}. Orange/blue show signed engineered coefficients.`;drawCircuit(f)}
function drawCircuit(){const dpr=devicePixelRatio||1;if(circuit.width!==Math.floor(circuit.clientWidth*dpr)){circuit.width=Math.floor(circuit.clientWidth*dpr);circuit.height=Math.floor(138*dpr);cx.setTransform(dpr,0,0,dpr,0,0)}const w=circuit.clientWidth,swarm=app.mode==='untrained'?blankSwarm:neuralSwarm,agent=swarm.agents[app.selected],activity=app.mode==='autopilot'?[]:agent.lastActivity,pos=new Map();cx.clearRect(0,0,w,138);circuitView.pn.forEach((n,i)=>pos.set(String(n.id),[22,13+i*13]));circuitView.kc.forEach((n,i)=>pos.set(String(n.id),[w*.48,8+i*6.1]));circuitView.edges.forEach(e=>{const a=pos.get(String(e.pre)),b=pos.get(String(e.post));if(!a||!b)return;cx.strokeStyle=`rgba(12,119,113,${Math.min(.5,.06+(+e.count||1)/30)})`;cx.beginPath();cx.moveTo(...a);cx.lineTo(...b);cx.stroke()});circuitView.pn.forEach(n=>{cx.fillStyle='#f4c95d';cx.beginPath();cx.arc(...pos.get(String(n.id)),4,0,Math.PI*2);cx.fill()});const outs=[[w-22,40],[w-22,86]];circuitView.kc.forEach(n=>{const p=pos.get(String(n.id)),i=swarm.topo.kc.indexOf(String(n.id)),a=Math.max(0,Math.min(1,activity[i]||0));cx.fillStyle=`rgba(12,119,113,${.2+a*.8})`;cx.beginPath();cx.arc(...p,3,0,Math.PI*2);cx.fill();outs.forEach((o,d)=>{const weight=agent.readout[d][i]||0,alpha=Math.min(.8,.05+Math.abs(weight)*2.5);cx.strokeStyle=weight>=0?`rgba(239,117,72,${alpha})`:`rgba(49,112,153,${alpha})`;cx.lineWidth=.5+Math.min(2,Math.abs(weight)*4);cx.beginPath();cx.moveTo(...p);cx.lineTo(...o);cx.stroke()})});outs.forEach((o,i)=>{cx.fillStyle=i?'#ef7548':'#317099';cx.beginPath();cx.arc(...o,6,0,Math.PI*2);cx.fill()});const weights=agent.readout.flat(),changed=weights.filter(v=>Math.abs(v)>1e-7).length,norm=Math.hypot(...weights);cx.fillStyle='#66817e';cx.font='600 8px system-ui';cx.fillText('PN',10,130);cx.fillText('KC · fixed anatomy',w*.48-34,130);cx.fillText('↔',w-27,25);cx.fillText('↑',w-25,105);cx.fillText(app.mode==='autopilot'?'engineering controller · neural graph idle':`${changed} changed weights · norm ${norm.toFixed(2)}`,60,130)}
function loop(now){const frame=Math.min(.05,(now-app.last)/1000);app.last=now;if(!app.paused){app.acc+=frame;while(app.acc>=1/120){app.forces=control(app.world);sim.stepWorld(app.world,app.forces,1/120);app.acc-=1/120;if(app.judge)sampleJudge()}}kitchenView.render(app.world,{mission:app.mission,selected:app.selected,paused:app.paused});updateUI();drawCircuitLabels();requestAnimationFrame(loop)}
function renderFlyPicker(){const w=app.world;$('#flyPicker').innerHTML=w.flies.map((f,i)=>`<button class="fly-chip ${i===app.selected?'active':''} ${!f.enabled?'disabled':''}" data-fly="${i}" aria-label="Select fly ${i+1}">${i+1}</button>`).join('');$('#flyTitle').textContent=`Fly ${app.selected+1} · ${app.selected<4?'Port':'Starboard'} ${Math.abs(app.selected-3.5)>2?'tip':'mid'}`;$('#toggleFly').textContent=w.flies[app.selected].enabled?'Remove':'Restore'}
function setTestLocked(on){$$('button,input').forEach(el=>{if(el.id!=='pauseButton')el.disabled=on})}
function sampleJudge(){const j=app.judge,w=app.world;if(!j.gusted&&w.time-j.start>=2){sim.applyGust(w,1);j.gusted=true}j.samples++;j.tilt+=Math.abs(w.angle);j.error+=Math.hypot(w.x-w.target.x,w.y-w.target.y);if(w.y>.35)j.aloft+=1/120;if(w.time-j.start>=8){const mt=j.tilt/j.samples*180/Math.PI,me=j.error/j.samples,passed=!!w.success;app.judge=null;updateScore({mt,me,aloft:j.aloft,grade:passed?'PASS':'TRY'});setTestLocked(false);$('#judgeButton').textContent='Run again';$('#judgeReplay').disabled=false}}
function updateScore(s){$('#scoreGrade').textContent=s?.grade||'—';$('#scoreAloft').textContent=s?`${s.aloft.toFixed(1)} / 8.0 s`:'—';$('#scoreTilt').textContent=s?`${s.mt.toFixed(1)}°`:'—';$('#scoreTarget').textContent=s?s.me.toFixed(2):'—'}

$$('.segment').forEach(b=>b.onclick=()=>{$$('.segment').forEach(x=>x.classList.toggle('active',x===b));app.mission=b.dataset.mission;reset();renderFlyPicker()});
$$('input[name=mode]').forEach(r=>r.onchange=()=>{app.mode=r.value;$('#statusText').textContent=r.value==='autopilot'?'Autopilot balancing':r.value==='learned'?'Learned readout active':'Zero-weight readout active'});
$('#massRange').oninput=e=>{$('#massOutput').textContent=`${(+e.target.value).toFixed(1)}×`;sim.setMass?sim.setMass(app.world,+e.target.value):app.world.mass=+e.target.value};
$('#gustButton').onclick=()=>sim.applyGust(app.world);$('#pauseButton').onclick=()=>{app.paused=!app.paused;$('#pauseButton').textContent=app.paused?'▶ Resume':'Ⅱ Pause';$('#statusDot').classList.toggle('paused',app.paused);$('#statusText').textContent=app.paused?'Experiment paused':`${app.mode[0].toUpperCase()+app.mode.slice(1)} active`};
$('#resetButton').onclick=()=>{reset();renderFlyPicker()};$('#replayButton').onclick=$('#resetButton').onclick;
$('#flyPicker').onclick=e=>{const b=e.target.closest('[data-fly]');if(!b)return;app.selected=+b.dataset.fly;renderFlyPicker()};$('#toggleFly').onclick=()=>{const f=app.world.flies[app.selected];f.enabled=!f.enabled;renderFlyPicker()};
$('#trainButton').onclick=async()=>{if(app.training)return;app.training=true;$('#trainButton').disabled=true;$('#trainStatus').textContent='Generating teacher trajectories and fitting readouts…';const worker=new Worker('./src/training-worker.js',{type:'module'}),finish=()=>{app.training=false;$('#trainButton').disabled=false;worker.terminate()};worker.postMessage({});worker.onerror=e=>{$('#trainStatus').textContent=`Training worker failed: ${e.message}`;finish()};worker.onmessage=e=>{if(e.data.progress){$('#trainFill').style.width=`${Math.round(e.data.progress.fraction*100)}%`;return}if(e.data.saved){neuralSwarm=neural.deserializeSwarm(evidence,e.data.saved);app.learned=true;try{localStorage.setItem('fly-swarm-learned',JSON.stringify(e.data.saved))}catch{$('#trainStatus').textContent='Training complete; browser storage is unavailable.'}$('#trainFill').style.width='100%';if(!$('#trainStatus').textContent.includes('unavailable'))$('#trainStatus').textContent=`Learned from ${neuralSwarm.training.samplesPerAgent} physics samples per fly.`}else $('#trainStatus').textContent=`Training failed: ${e.data.error}`;finish()}}
$('#resetLearning').onclick=()=>{neuralSwarm=neural.createSwarm(evidence,{agentCount:8,seed:7401});app.learned=null;try{localStorage.removeItem('fly-swarm-learned')}catch{}$('#trainFill').style.width='0';$('#trainStatus').textContent='Learned memory cleared. Anatomy remains fixed.'};
$('#trainButton').addEventListener('click',()=>{if(!app.training)return;$('#resetLearning').disabled=true;const watch=()=>{if(app.training)requestAnimationFrame(watch);else $('#resetLearning').disabled=false};requestAnimationFrame(watch)});
function startJudge(replay=false){if(app.training)return;if(!replay)app.judgeSnapshot={seed:$('#seedInput').value,mass:+$('#massRange').value,mission:app.mission,mode:app.mode,target:{...app.world.target},disabled:app.world.flies.filter(f=>!f.enabled).map(f=>f.index),readout:neural.serializeSwarm(neuralSwarm)};const s=app.judgeSnapshot;$('#seedInput').value=s.seed;$('#massRange').value=s.mass;$('#massOutput').textContent=`${s.mass.toFixed(1)}×`;app.mission=s.mission;app.mode=s.mode;$$('.segment').forEach(b=>b.classList.toggle('active',b.dataset.mission===s.mission));$$('input[name=mode]').forEach(r=>r.checked=r.value===s.mode);neuralSwarm=neural.deserializeSwarm(evidence,s.readout);app.paused=false;$('#pauseButton').textContent='Ⅱ Pause';$('#statusDot').classList.remove('paused');reset();app.world.target={...s.target};updateTargetInputs();app.world.flies.forEach(f=>f.enabled=!s.disabled.includes(f.index));renderFlyPicker();app.judge={start:app.world.time,samples:0,tilt:0,error:0,aloft:0,gusted:false};setTestLocked(true);$('#pauseButton').disabled=false;$('#judgeButton').textContent='Testing…';updateScore(null)}

function drawCircuitLabels(){const w=circuit.clientWidth;cx.fillStyle='#fffef9';cx.fillRect(w-42,12,40,104);cx.fillStyle='#163b39';cx.font='700 10px system-ui';cx.fillText('Fx',w-28,43);cx.fillText('Fy',w-28,90);cx.fillStyle='#66817e';cx.font='600 10px system-ui';cx.fillText('subset: 8 PN · 18 KC',8,116)}
$('#judgeButton').onclick=()=>startJudge(false);$('#judgeReplay').onclick=()=>startJudge(true);
$('#cameraReset').onclick=()=>kitchenView.resetCamera();$('#cameraAngle').onclick=()=>kitchenView.setCameraPreset('angled');$('#cameraFront').onclick=()=>kitchenView.setCameraPreset('front');$('#cameraCrew').onclick=()=>kitchenView.setCameraPreset('crew');
function updateTargetInputs(){if(!app.world)return;$('#targetX').value=app.world.target.x.toFixed(1);$('#targetY').value=app.world.target.y.toFixed(1)}
function clampTarget(){app.world.target.x=Math.max(-4.4,Math.min(4.4,app.world.target.x));app.world.target.y=Math.max(.2,Math.min(4.5,app.world.target.y))}
for(const [id,axis] of [['targetX','x'],['targetY','y']])$('#'+id).onchange=e=>{if(app.judge)return;const value=Number(e.target.value);if(Number.isFinite(value))app.world.target[axis]=value;clampTarget();updateTargetInputs();$('#sceneHint').textContent=`Target moved to ${app.world.target.x.toFixed(1)}, ${app.world.target.y.toFixed(1)}`};
canvas.tabIndex=0;canvas.onkeydown=e=>{if(app.judge)return;const d=.2;if(e.key==='ArrowLeft')app.world.target.x-=d;else if(e.key==='ArrowRight')app.world.target.x+=d;else if(e.key==='ArrowUp')app.world.target.y+=d;else if(e.key==='ArrowDown')app.world.target.y-=d;else return;clampTarget();updateTargetInputs();$('#sceneHint').textContent=`Target moved to ${app.world.target.x.toFixed(1)}, ${app.world.target.y.toFixed(1)}`;e.preventDefault()};
reset();renderFlyPicker();requestAnimationFrame(loop);
