import * as sim from './physics.js';
import * as neural from './neural.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#world'), ctx=canvas.getContext('2d'), circuit=$('#circuit'), cx=circuit.getContext('2d');
const app={world:null,paused:false,last:performance.now(),acc:0,selected:0,mode:'autopilot',mission:'balance',forces:Array(8).fill(0),judge:null,training:false,learned:null};

async function loadEvidence(){for(const path of ['./data/circuit.json']){try{const r=await fetch(path);if(r.ok)return await r.json()}catch{}}return null}
const evidence=await loadEvidence();
if(!evidence)throw new Error('Required anatomical circuit data could not be loaded.');
let neuralSwarm=neural.createSwarm(evidence,{agentCount:8,seed:7401});
let blankSwarm=neural.createSwarm(evidence,{agentCount:8,seed:7401});
async function restoreLearned(){let local=null;try{local=localStorage.getItem('fly-swarm-learned');if(local){neuralSwarm=neural.deserializeSwarm(evidence,JSON.parse(local));app.learned=true;return}}catch(error){console.warn('Ignoring stale saved readout:',error);try{localStorage.removeItem('fly-swarm-learned')}catch{}}try{const r=await fetch('./evidence/trained-session.json');if(!r.ok)throw new Error(`HTTP ${r.status}`);neuralSwarm=neural.deserializeSwarm(evidence,await r.json());app.learned=true}catch(error){console.warn('Shipped trained session unavailable:',error)}}
await restoreLearned();
const circuitView=(()=>{const pn=evidence.neurons.filter(n=>n.role==='projection_neuron').slice(0,8),kc=evidence.neurons.filter(n=>n.role==='kenyon_cell').slice(0,18),ids=new Set([...pn,...kc].map(n=>String(n.id))),edges=evidence.edges.filter(e=>e.relation==='pn_to_kc'&&ids.has(String(e.pre))&&ids.has(String(e.post)));return{pn,kc,edges}})();
$('#evidenceSummary').textContent=`Evidence: ${evidence.neurons.length.toLocaleString()} neurons · ${evidence.edges.length.toLocaleString()} anatomical edges.`;
fetch('./evidence/experiment-results.json').then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(x=>{const h=x.summaryByGroup?.learned?.heldOutInterpolation,s=x.summaryByGroup?.learned?.stressExtrapolation;if(h&&s)$('#evidenceSummary').textContent+=` Frozen evaluation: ${h.successes}/${h.trials} held-out; ${s.successes}/${s.trials} stress.`}).catch(()=>{$('#evidenceSummary').textContent+=' Frozen evaluation file unavailable.'});
function hashSeed(s){let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0}
function reset(){const mass=+$('#massRange').value;app.world=sim.createWorld({seed:hashSeed($('#seedInput').value),mass,target:{x:app.mission==='carry'?1.7:0,y:app.mission==='carry'?1.7:2.05},tilt:0,disabled:[]});app.last=performance.now();app.acc=0;app.judge=null;updateScore(null)}
function control(w){if(app.mode==='autopilot')return sim.baselineForces(w);return neural.swarmForces(app.mode==='untrained'?blankSwarm:neuralSwarm,w)}
function fit(){const d=devicePixelRatio||1,r=canvas.parentElement.getBoundingClientRect();if(canvas.width!==Math.floor(r.width*d)||canvas.height!==Math.floor(r.height*d)){canvas.width=Math.floor(r.width*d);canvas.height=Math.floor(r.height*d);ctx.setTransform(d,0,0,d,0,0)}}
function draw(){fit();const W=canvas.clientWidth,H=canvas.clientHeight,w=app.world;ctx.clearRect(0,0,W,H);
  const grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#dcece4');grad.addColorStop(.62,'#f7ead2');grad.addColorStop(1,'#d3a77b');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);
  ctx.fillStyle='rgba(255,255,255,.32)';ctx.fillRect(W*.08,0,W*.23,H*.55);ctx.strokeStyle='rgba(22,59,57,.11)';ctx.lineWidth=2;for(let x=W*.08;x<W*.31;x+=W*.075){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H*.55);ctx.stroke()}ctx.fillStyle='#bd6e49';ctx.fillRect(0,H*.81,W,H*.19);ctx.fillStyle='#f5ddbb';ctx.fillRect(0,H*.78,W,H*.045);
  drawKitchen(W,H);const sx=Math.min(W/12,H*.70/6),ox=W/2+w.x*sx,oy=H*.78-w.y*sx,targetX=W/2+w.target.x*sx,targetY=H*.78-w.target.y*sx;
  ctx.strokeStyle='#0c7771';ctx.lineWidth=2;ctx.setLineDash([5,6]);ctx.beginPath();ctx.arc(targetX,targetY,20,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#0c7771';ctx.font='700 10px Manrope';ctx.fillText('TARGET',targetX-21,targetY-27);
  if(app.mission==='carry'){ctx.fillStyle='rgba(255,255,255,.9)';ctx.strokeStyle='#9fbdb4';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(targetX,targetY+28,32,9,0,0,Math.PI*2);ctx.fill();ctx.stroke()}
  ctx.save();ctx.translate(ox,oy);ctx.rotate(-w.angle);ctx.shadowColor='rgba(50,40,20,.25)';ctx.shadowBlur=10;ctx.shadowOffsetY=7;ctx.fillStyle='#8b5d3e';roundRect(ctx,-1.4*sx,-8,2.8*sx,16,7);ctx.fill();ctx.shadowColor='transparent';
  if(app.mission==='carry'){ctx.fillStyle='#77a94e';ctx.beginPath();ctx.arc(0,-22,16,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#47742e';ctx.stroke();ctx.fillStyle='#47742e';ctx.fillRect(-2,-39,4,7)}
  w.flies.forEach((f,i)=>{const x=f.attachment*sx,y=-38-Math.sin(w.time*8+i)*3;ctx.strokeStyle='rgba(22,59,57,.3)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(f.attachment*sx,0);ctx.lineTo(x,y+9);ctx.stroke();drawFly(ctx,x,y,i,f.enabled,i===app.selected,w.time);if(f.enabled&&Math.hypot(f.fx,f.fy)>.05){const dx=f.fx*3,dy=-f.fy*4,c=Math.cos(w.angle),s=Math.sin(w.angle),lx=c*dx-s*dy,ly=s*dx+c*dy;ctx.strokeStyle='rgba(239,117,72,.62)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y-13);ctx.lineTo(x+lx,y-13+ly);ctx.stroke();ctx.fillStyle='#ef7548';ctx.beginPath();ctx.arc(x+lx,y-13+ly,3,0,Math.PI*2);ctx.fill()}});ctx.restore();
  if(w.y<.3){ctx.fillStyle='rgba(164,61,36,.9)';ctx.font='800 18px Manrope';ctx.textAlign='center';ctx.fillText('Oof. Reset and try another controller.',W/2,H*.7);ctx.textAlign='left'}
}
function drawKitchen(W,H){ctx.strokeStyle='rgba(22,59,57,.08)';ctx.lineWidth=1;for(let x=0;x<W;x+=52){ctx.beginPath();ctx.moveTo(x,H*.42);ctx.lineTo(x,H*.78);ctx.stroke()}for(let y=H*.42;y<H*.78;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle='rgba(255,255,255,.5)';roundRect(ctx,W*.7,H*.08,W*.22,H*.32,14);ctx.fill();ctx.fillStyle='#0f716c';ctx.fillRect(W*.71,H*.1,W*.2,8);ctx.fillStyle='#ef7548';ctx.fillRect(W*.76,H*.13,9,H*.22);ctx.fillStyle='#f4c95d';ctx.fillRect(W*.79,H*.16,13,H*.19);ctx.fillStyle='#fff';roundRect(ctx,W*.58,H*.69,42,54,8);ctx.fill();ctx.strokeStyle='#b8cfc5';ctx.stroke();ctx.fillStyle='#66817e';ctx.font='700 9px system-ui';ctx.fillText('FLOUR',W*.585,H*.75);ctx.fillStyle='#8cb66a';ctx.fillRect(W*.36,H*.7,36,15);for(let i=0;i<5;i++){ctx.strokeStyle='#47742e';ctx.beginPath();ctx.moveTo(W*.38,H*.7);ctx.lineTo(W*.365+i*7,H*.64-(i%2)*8);ctx.stroke()}ctx.strokeStyle='#657d78';ctx.lineWidth=2;ctx.fillStyle='transparent';for(let i=0;i<3;i++){const x=W*(.42+i*.055);ctx.beginPath();ctx.arc(x,H*.1,5,Math.PI,0);ctx.stroke();ctx.beginPath();ctx.moveTo(x+5,H*.1);ctx.lineTo(x+5,H*.23);ctx.stroke()}ctx.fillStyle='#fff';ctx.beginPath();ctx.ellipse(W*.14,H*.84,W*.105,H*.035,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#b8cfc5';ctx.stroke();ctx.strokeStyle='#657d78';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(W*.82,H*.77);ctx.lineTo(W*.95,H*.57);ctx.stroke();ctx.fillStyle='#657d78';roundRect(ctx,W*.76,H*.72,W*.1,H*.055,12);ctx.fill()}
function drawFly(g,x,y,i,on,selected,t){g.save();g.translate(x,y);g.globalAlpha=on?1:.22;if(selected){g.strokeStyle='#ef7548';g.lineWidth=2;g.beginPath();g.arc(0,0,18,0,Math.PI*2);g.stroke()}g.strokeStyle='#263c39';g.lineWidth=1;for(const side of [-1,1]){g.beginPath();g.moveTo(side*3,3);g.lineTo(side*9,9);g.lineTo(side*12,12);g.stroke();g.beginPath();g.moveTo(side*2,-5);g.quadraticCurveTo(side*6,-12,side*9,-11);g.stroke()}g.fillStyle='rgba(255,255,255,.78)';const flap=Math.sin(t*28+i)*.28;g.save();g.rotate(-.7-flap);g.beginPath();g.ellipse(-8,0,9,4,0,0,Math.PI*2);g.fill();g.restore();g.save();g.rotate(.7+flap);g.beginPath();g.ellipse(8,0,9,4,0,0,Math.PI*2);g.fill();g.restore();g.fillStyle='#263c39';g.beginPath();g.ellipse(0,1,5,8,0,0,Math.PI*2);g.fill();g.fillStyle='#ef7548';g.beginPath();g.arc(-3,-5,2.4,0,Math.PI*2);g.arc(3,-5,2.4,0,Math.PI*2);g.fill();g.fillStyle='#fff';g.beginPath();g.arc(-2.3,-5.7,.7,0,Math.PI*2);g.arc(3.7,-5.7,.7,0,Math.PI*2);g.fill();g.restore()}
function roundRect(g,x,y,w,h,r){g.beginPath();g.roundRect(x,y,w,h,r)}
function updateUI(){const w=app.world;$('#balanceReadout').textContent=`${(w.angle*180/Math.PI).toFixed(1)}°`;$('#heightReadout').textContent=w.y.toFixed(2);$('#timeReadout').textContent=`${w.time.toFixed(1)} s`;const f=w.flies[app.selected],lift=w.flies.reduce((s,x)=>s+x.fy,0),load=w.mass*sim.GRAVITY,effort=w.flies.reduce((s,x)=>s+Math.hypot(x.fx,x.fy),0),swarm=app.mode==='untrained'?blankSwarm:neuralSwarm,weights=swarm.agents[app.selected].readout.flat(),changed=weights.filter(v=>Math.abs(v)>1e-7).length,norm=Math.hypot(...weights);$('#forceReadout').textContent=`${lift.toFixed(1)} / ${load.toFixed(1)} · Σ${effort.toFixed(1)}`;$('#senseHeight').textContent=(w.target.y-w.y>=0?'+':'')+(w.target.y-w.y).toFixed(2);$('#senseTilt').textContent=`${(w.angle*180/Math.PI).toFixed(1)}°`;$('#senseVelocity').textContent=w.vy.toFixed(2);$('#senseThrust').textContent=`${Math.round((f?.fy||0)/8*100)}%`;$('#readoutSummary').textContent=app.mode==='autopilot'?'Engineering controller active; neural graph is idle.':`Fly ${app.selected+1}: ${changed} changed readout weights · norm ${norm.toFixed(2)} · sample KC ${swarm.topo.kc[0]}. Orange/blue show signed engineered coefficients.`;drawCircuit(f)}
function drawCircuit(){const dpr=devicePixelRatio||1;if(circuit.width!==Math.floor(circuit.clientWidth*dpr)){circuit.width=Math.floor(circuit.clientWidth*dpr);circuit.height=Math.floor(138*dpr);cx.setTransform(dpr,0,0,dpr,0,0)}const w=circuit.clientWidth,swarm=app.mode==='untrained'?blankSwarm:neuralSwarm,agent=swarm.agents[app.selected],activity=app.mode==='autopilot'?[]:agent.lastActivity,pos=new Map();cx.clearRect(0,0,w,138);circuitView.pn.forEach((n,i)=>pos.set(String(n.id),[22,13+i*13]));circuitView.kc.forEach((n,i)=>pos.set(String(n.id),[w*.48,8+i*6.1]));circuitView.edges.forEach(e=>{const a=pos.get(String(e.pre)),b=pos.get(String(e.post));if(!a||!b)return;cx.strokeStyle=`rgba(12,119,113,${Math.min(.5,.06+(+e.count||1)/30)})`;cx.beginPath();cx.moveTo(...a);cx.lineTo(...b);cx.stroke()});circuitView.pn.forEach(n=>{cx.fillStyle='#f4c95d';cx.beginPath();cx.arc(...pos.get(String(n.id)),4,0,Math.PI*2);cx.fill()});const outs=[[w-22,40],[w-22,86]];circuitView.kc.forEach(n=>{const p=pos.get(String(n.id)),i=swarm.topo.kc.indexOf(String(n.id)),a=Math.max(0,Math.min(1,activity[i]||0));cx.fillStyle=`rgba(12,119,113,${.2+a*.8})`;cx.beginPath();cx.arc(...p,3,0,Math.PI*2);cx.fill();outs.forEach((o,d)=>{const weight=agent.readout[d][i]||0,alpha=Math.min(.8,.05+Math.abs(weight)*2.5);cx.strokeStyle=weight>=0?`rgba(239,117,72,${alpha})`:`rgba(49,112,153,${alpha})`;cx.lineWidth=.5+Math.min(2,Math.abs(weight)*4);cx.beginPath();cx.moveTo(...p);cx.lineTo(...o);cx.stroke()})});outs.forEach((o,i)=>{cx.fillStyle=i?'#ef7548':'#317099';cx.beginPath();cx.arc(...o,6,0,Math.PI*2);cx.fill()});const weights=agent.readout.flat(),changed=weights.filter(v=>Math.abs(v)>1e-7).length,norm=Math.hypot(...weights);cx.fillStyle='#66817e';cx.font='600 8px system-ui';cx.fillText('PN',10,130);cx.fillText('KC · fixed anatomy',w*.48-34,130);cx.fillText('↔',w-27,25);cx.fillText('↑',w-25,105);cx.fillText(app.mode==='autopilot'?'engineering controller · neural graph idle':`${changed} changed weights · norm ${norm.toFixed(2)}`,60,130)}
function loop(now){const frame=Math.min(.05,(now-app.last)/1000);app.last=now;if(!app.paused){app.acc+=frame;while(app.acc>=1/120){app.forces=control(app.world);sim.stepWorld(app.world,app.forces,1/120);app.acc-=1/120;if(app.judge)sampleJudge()}}draw();updateUI();drawCircuitLabels();requestAnimationFrame(loop)}
function renderFlyPicker(){const w=app.world;$('#flyPicker').innerHTML=w.flies.map((f,i)=>`<button class="fly-chip ${i===app.selected?'active':''} ${!f.enabled?'disabled':''}" data-fly="${i}" aria-label="Select fly ${i+1}">${i+1}</button>`).join('');$('#flyTitle').textContent=`Fly ${app.selected+1} · ${app.selected<4?'Port':'Starboard'} ${Math.abs(app.selected-3.5)>2?'tip':'mid'}`;$('#toggleFly').textContent=w.flies[app.selected].enabled?'Remove':'Restore'}
function setTestLocked(on){$$('button,input').forEach(el=>{if(el.id!=='pauseButton')el.disabled=on})}
function sampleJudge(){const j=app.judge,w=app.world;if(!j.gusted&&w.time-j.start>=2){sim.applyGust(w,1);j.gusted=true}j.samples++;j.tilt+=Math.abs(w.angle);j.error+=Math.hypot(w.x-w.target.x,w.y-w.target.y);if(w.y>.35)j.aloft+=1/120;if(w.time-j.start>=8){const mt=j.tilt/j.samples*180/Math.PI,me=j.error/j.samples,passed=!!w.success;app.judge=null;updateScore({mt,me,aloft:j.aloft,grade:passed?'PASS':'TRY'});setTestLocked(false);$('#judgeButton').textContent='Run again';$('#judgeReplay').disabled=false}}
function updateScore(s){$('#scoreGrade').textContent=s?.grade||'—';$('#scoreAloft').textContent=s?`${s.aloft.toFixed(1)} / 8.0 s`:'—';$('#scoreTilt').textContent=s?`${s.mt.toFixed(1)}°`:'—';$('#scoreTarget').textContent=s?s.me.toFixed(2):'—'}

$$('.segment').forEach(b=>b.onclick=()=>{$$('.segment').forEach(x=>x.classList.toggle('active',x===b));app.mission=b.dataset.mission;reset();renderFlyPicker()});
$$('input[name=mode]').forEach(r=>r.onchange=()=>{app.mode=r.value;$('#statusText').textContent=r.value==='autopilot'?'Autopilot balancing':r.value==='learned'?'Learned readout active':'Zero-weight readout active'});
$('#massRange').oninput=e=>{$('#massOutput').textContent=`${(+e.target.value).toFixed(1)}×`;sim.setMass?sim.setMass(app.world,+e.target.value):app.world.mass=+e.target.value};
$('#gustButton').onclick=()=>sim.applyGust(app.world);$('#pauseButton').onclick=()=>{app.paused=!app.paused;$('#pauseButton').textContent=app.paused?'▶ Resume':'Ⅱ Pause';$('#statusDot').classList.toggle('paused',app.paused);$('#statusText').textContent=app.paused?'Experiment paused':`${app.mode[0].toUpperCase()+app.mode.slice(1)} active`};
$('#resetButton').onclick=()=>{reset();renderFlyPicker()};$('#replayButton').onclick=$('#resetButton').onclick;
$('#flyPicker').onclick=e=>{const b=e.target.closest('[data-fly]');if(!b)return;app.selected=+b.dataset.fly;renderFlyPicker()};$('#toggleFly').onclick=()=>{const f=app.world.flies[app.selected];f.enabled=!f.enabled;renderFlyPicker()};
$('#trainButton').onclick=async()=>{if(app.training)return;app.training=true;$('#trainButton').disabled=true;$('#trainStatus').textContent='Generating teacher trajectories and fitting readouts…';const worker=new Worker('./src/training-worker.js',{type:'module'}),finish=()=>{app.training=false;$('#trainButton').disabled=false;worker.terminate()};worker.postMessage({});worker.onerror=e=>{$('#trainStatus').textContent=`Training worker failed: ${e.message}`;finish()};worker.onmessage=e=>{if(e.data.progress){$('#trainFill').style.width=`${Math.round(e.data.progress.fraction*100)}%`;return}if(e.data.saved){neuralSwarm=neural.deserializeSwarm(evidence,e.data.saved);app.learned=true;try{localStorage.setItem('fly-swarm-learned',JSON.stringify(e.data.saved))}catch{$('#trainStatus').textContent='Training complete; browser storage is unavailable.'}$('#trainFill').style.width='100%';if(!$('#trainStatus').textContent.includes('unavailable'))$('#trainStatus').textContent=`Learned from ${neuralSwarm.training.samplesPerAgent} physics samples per fly.`}else $('#trainStatus').textContent=`Training failed: ${e.data.error}`;finish()}}
$('#resetLearning').onclick=()=>{neuralSwarm=neural.createSwarm(evidence,{agentCount:8,seed:7401});app.learned=null;try{localStorage.removeItem('fly-swarm-learned')}catch{}$('#trainFill').style.width='0';$('#trainStatus').textContent='Learned memory cleared. Anatomy remains fixed.'};
$('#trainButton').addEventListener('click',()=>{if(!app.training)return;$('#resetLearning').disabled=true;const watch=()=>{if(app.training)requestAnimationFrame(watch);else $('#resetLearning').disabled=false};requestAnimationFrame(watch)});
function startJudge(replay=false){if(app.training)return;if(!replay)app.judgeSnapshot={seed:$('#seedInput').value,mass:+$('#massRange').value,mission:app.mission,mode:app.mode,target:{...app.world.target},disabled:app.world.flies.filter(f=>!f.enabled).map(f=>f.index),readout:neural.serializeSwarm(neuralSwarm)};const s=app.judgeSnapshot;$('#seedInput').value=s.seed;$('#massRange').value=s.mass;$('#massOutput').textContent=`${s.mass.toFixed(1)}×`;app.mission=s.mission;app.mode=s.mode;$$('.segment').forEach(b=>b.classList.toggle('active',b.dataset.mission===s.mission));$$('input[name=mode]').forEach(r=>r.checked=r.value===s.mode);neuralSwarm=neural.deserializeSwarm(evidence,s.readout);app.paused=false;$('#pauseButton').textContent='Ⅱ Pause';$('#statusDot').classList.remove('paused');reset();app.world.target={...s.target};app.world.flies.forEach(f=>f.enabled=!s.disabled.includes(f.index));renderFlyPicker();app.judge={start:app.world.time,samples:0,tilt:0,error:0,aloft:0,gusted:false};setTestLocked(true);$('#pauseButton').disabled=false;$('#judgeButton').textContent='Testing…';updateScore(null)}

function drawCircuitLabels(){const w=circuit.clientWidth;cx.fillStyle='#fffef9';cx.fillRect(w-42,12,40,104);cx.fillStyle='#163b39';cx.font='700 10px system-ui';cx.fillText('Fx',w-28,43);cx.fillText('Fy',w-28,90);cx.fillStyle='#66817e';cx.font='600 10px system-ui';cx.fillText('subset: 8 PN · 18 KC',8,116)}
$('#judgeButton').onclick=()=>startJudge(false);$('#judgeReplay').onclick=()=>startJudge(true);
function clampTarget(){app.world.target.x=Math.max(-4.4,Math.min(4.4,app.world.target.x));app.world.target.y=Math.max(.2,Math.min(4.5,app.world.target.y))}canvas.onclick=e=>{if(app.judge)return;const r=canvas.getBoundingClientRect(),sx=Math.min(r.width/12,r.height*.70/6);app.world.target.x=(e.clientX-r.left-r.width/2)/sx;app.world.target.y=(r.height*.78-(e.clientY-r.top))/sx;clampTarget();$('#sceneHint').textContent=`Target moved to ${app.world.target.x.toFixed(1)}, ${app.world.target.y.toFixed(1)}`};canvas.tabIndex=0;canvas.onkeydown=e=>{if(app.judge)return;const d=.2;if(e.key==='ArrowLeft')app.world.target.x-=d;else if(e.key==='ArrowRight')app.world.target.x+=d;else if(e.key==='ArrowUp')app.world.target.y+=d;else if(e.key==='ArrowDown')app.world.target.y-=d;else return;clampTarget();e.preventDefault()};
reset();renderFlyPicker();requestAnimationFrame(loop);

