// Connectome-constrained random-feature controller.
// The anatomical claim is deliberately narrow: raw PN→KC contact counts define the
// fixed hidden layer. Observation encoding and the action readout are engineered.

import { createWorld, stepWorld, baselineForces, observations, applyGust, MAX_FORCE } from './physics.js';
import { fitRidge } from './ridge.js';

const OBS_COUNT = 15;

const clamp = (x, lo, hi) => Math.max(lo, Math.min(hi, x));
function hash(s) {
  let h = 2166136261;
  for (const c of String(s)) { h ^= c.charCodeAt(0); h = Math.imul(h, 16777619); }
  h ^= h >>> 16; h = Math.imul(h, 0x7feb352d); h ^= h >>> 15; h = Math.imul(h, 0x846ca68b); h ^= h >>> 16;
  return h >>> 0;
}
function rng(seed) { let x = seed >>> 0 || 1; return () => ((x ^= x << 13, x ^= x >>> 17, x ^= x << 5) >>> 0) / 4294967296; }

export function encodeObservation(observation = {}, agentIndex = 0) {
  if (Array.isArray(observation)) return observation.slice(0, OBS_COUNT).concat(Array(OBS_COUNT).fill(0)).slice(0, OBS_COUNT).map(v => Number.isFinite(Number(v)) ? Number(v) : 0);
  return new Array(OBS_COUNT).fill(0);
}

function topology(circuit) {
  const pn = circuit.neurons.filter(n => n.role === 'projection_neuron').map(n => String(n.id));
  const kc = circuit.neurons.filter(n => n.role === 'kenyon_cell').map(n => String(n.id));
  const pi = new Map(pn.map((id, i) => [id, i])), ki = new Map(kc.map((id, i) => [id, i]));
  const incoming = Array.from({ length: kc.length }, () => []);
  for (const e of circuit.edges) if (e.relation === 'pn_to_kc' && pi.has(String(e.pre)) && ki.has(String(e.post))) incoming[ki.get(String(e.post))].push([pi.get(String(e.pre)), Number(e.count)]);
  for (const list of incoming) { const sum = list.reduce((a, x) => a + x[1], 0) || 1; for (const x of list) x[1] /= sum; }
  return { pn, kc, incoming };
}

function encoder(pnIds, agent, obsN) {
  return pnIds.map(id => Array.from({ length: obsN + 1 }, (_, j) => {
    const u = hash(`${id}:${agent}:${j}`) / 4294967296;
    return 1.25 * Math.sin(6.283185307 * u);
  }));
}

export function createSwarm(circuit, options = {}) {
  if (!circuit?.neurons || !circuit?.edges) throw new Error('A circuit with neurons and edges is required');
  const topo = topology(circuit), agentCount = options.agentCount ?? 8;
  const agents = Array.from({ length: agentCount }, (_, i) => ({
    encoder: encoder(topo.pn, i, OBS_COUNT),
    readout: [new Array(topo.kc.length + 1).fill(0), new Array(topo.kc.length + 1).fill(0)],
    lastActivity: new Array(topo.kc.length).fill(0)
  }));
  return { version: 2, encodingId: 'obs15-fnv-avalanche-tanh-v1', kind: 'PN-KC fixed-topology supervised readout', agentCount, topo, agents,
    trained: false, seed: options.seed ?? 7401, metadata: { anatomicalLayer: 'normalized raw PN→KC contact counts', engineered: ['observation-to-PN encoding', 'KC nonlinearity', 'action readout'] } };
}

function activity(swarm, obs, ai, mode) {
  const a = swarm.agents[ai], x = encodeObservation(obs, ai);
  const pn = a.encoder.map(row => Math.tanh(row[row.length - 1] * .35 + row.slice(0, -1).reduce((s, w, j) => s + w * x[j], 0)));
  let incoming = swarm.topo.incoming;
  if (mode === 'scrambled') incoming = incoming.map((_, k) => swarm.topo.incoming[(k * 73 + 19) % incoming.length]);
  const raw = incoming.map(list => Math.tanh(1.8 * list.reduce((s, [p, w]) => s + pn[p] * w, 0)));
  if (mode === 'clamped') raw.fill(0);
  const kc = raw;
  a.lastActivity = kc;
  return kc;
}

export function trainSwarm(circuit, options = {}, onProgress) {
  const swarm = options.swarm || createSwarm(circuit, options);
  const samples = options.samples ?? 2400, ridgeLambda = options.ridgeLambda ?? 1e-3;
  const rand = rng(options.seed ?? swarm.seed), data = Array.from({ length: swarm.agentCount }, () => []);
  // Teacher trajectories are generated by the physics module's analytic PD allocator.
  // Training seeds are deliberately recorded so evaluation can exclude them.
  const trainingSeeds = [];
  const randomSamples = Math.floor(samples / 2);
  for (let t = 0; t < randomSamples; t++) {
    const seed = 1000 + t; trainingSeeds.push(seed);
    const disabled = rand() < .35 ? [Math.floor(rand() * swarm.agentCount)] : [];
    const world = createWorld({ seed, mass: .55 + rand() * 2.2, x: (rand() - .5) * 7, y: .4 + rand() * 4.8,
      vx: (rand() - .5) * 5, vy: (rand() - .5) * 4, tilt: (rand() - .5) * 1.4,
      omega: (rand() - .5) * 4, target: { x: (rand() - .5) * 7, y: .8 + rand() * 4.2 }, disabled });
    const target = baselineForces(world);
    for (let ai = 0; ai < swarm.agentCount; ai++) data[ai].push([activity(swarm, observations(world, ai), ai), [target[ai].fx / MAX_FORCE, target[ai].fy / MAX_FORCE]]);
  }
  let rollout = null;
  for (let t = randomSamples; t < samples; t++) {
    if (!rollout || t % 160 === 0) {
      const seed = 1000 + t; trainingSeeds.push(seed);
      rollout = createWorld({ seed, mass: .65 + rand() * 1.8, x: (rand() - .5) * 3, y: .5 + rand() * 2,
        tilt: (rand() - .5) * .9, target: { x: (rand() - .5) * 7, y: 1 + rand() * 3.5 },
        disabled: rand() < .3 ? [Math.floor(rand() * swarm.agentCount)] : [] });
    }
    if (t % 83 === 30) applyGust(rollout, .4 + rand());
    const target = baselineForces(rollout);
    for (let ai = 0; ai < swarm.agentCount; ai++) data[ai].push([activity(swarm, observations(rollout, ai), ai), [target[ai].fx / MAX_FORCE, target[ai].fy / MAX_FORCE]]);
    stepWorld(rollout, target);
  }
  for (let ai = 0; ai < swarm.agentCount; ai++) {
    const x = data[ai].map(([k]) => [...k, 1]);
    const y = data[ai].map(([, target]) => target);
    const fitted = fitRidge(x, y, ridgeLambda);
    swarm.agents[ai].readout = fitted.map(row => Array.from(row));
    onProgress?.({ agent: ai + 1, agentCount: swarm.agentCount, fraction: (ai + 1) / swarm.agentCount });
  }
  swarm.trained = true;
  let squaredError = 0, values = 0;
  for (let ai = 0; ai < swarm.agentCount; ai++) for (const [k, y] of data[ai]) for (let d = 0; d < 2; d++) {
    const w = swarm.agents[ai].readout[d]; let pred = w[w.length - 1]; for (let j = 0; j < k.length; j++) pred += w[j] * k[j];
    squaredError += (pred - y[d]) ** 2; values++;
  }
  swarm.training = { method: 'ridge-regression imitation of physics baselineForces PD allocator', samplesPerAgent: samples, ridgeLambda, seed: options.seed ?? swarm.seed,
    trainingSeedRanges: [{ from: 1000, to: 1000 + randomSamples - 1 }, { rolloutStarts: trainingSeeds.slice(randomSamples) }], finalTrainingMSE: squaredError / values };
  return swarm;
}

export function controllerAction(swarm, observation, agentIndex = 0, options = {}) {
  const mode = options.ablation || 'none';
  const k = activity(swarm, observation, agentIndex, mode), out = [0, 0];
  for (let d = 0; d < 2; d++) { const w = swarm.agents[agentIndex].readout[d]; out[d] = w[w.length - 1]; for (let j = 0; j < k.length; j++) out[d] += w[j] * k[j]; }
  const fx = clamp(out[0], -1, 1) * MAX_FORCE, fy = clamp(out[1], -1, 1) * MAX_FORCE;
  return { fx, fy, lift: fy / MAX_FORCE, lateral: fx / MAX_FORCE, thrust: fy / MAX_FORCE, torque: fx / MAX_FORCE };
}

export function swarmForces(swarm, world, options = {}) {
  if (options.ablation === 'pd') return baselineForces(world);
  return Array.from({ length: swarm.agentCount }, (_, i) => controllerAction(swarm, observations(world, i), i, options));
}

export function serializeSwarm(swarm) {
  return { version: swarm.version, encodingId: swarm.encodingId, kind: swarm.kind, agentCount: swarm.agentCount, seed: swarm.seed, trained: swarm.trained,
    training: swarm.training, metadata: swarm.metadata, pnIds: swarm.topo.pn, kcIds: swarm.topo.kc,
    readouts: swarm.agents.map(a => a.readout) };
}

export function deserializeSwarm(circuit, saved) {
  if (saved?.version !== 2 || saved?.encodingId !== 'obs15-fnv-avalanche-tanh-v1') throw new Error('Unsupported or stale serialized neural model');
  const swarm = createSwarm(circuit, { agentCount: saved.agentCount, seed: saved.seed });
  if (saved.pnIds?.join('|') !== swarm.topo.pn.join('|') || saved.kcIds?.join('|') !== swarm.topo.kc.join('|')) throw new Error('Serialized readout does not match circuit topology');
  if (!Array.isArray(saved.readouts) || saved.readouts.length !== swarm.agentCount || saved.readouts.some(r => !Array.isArray(r) || r.length !== 2 || r.some(row => !Array.isArray(row) || row.length !== swarm.topo.kc.length + 1 || row.some(v => !Number.isFinite(v)))))
    throw new Error('Serialized neural readouts are malformed');
  saved.readouts.forEach((r, i) => { swarm.agents[i].readout = r.map(x => [...x]); });
  swarm.trained = !!saved.trained; swarm.training = saved.training; return swarm;
}

export const neuralConstants = { observationCount: OBS_COUNT };
